config/routes.rb
Rails.application.routes.draw do
  resources :kpi_notifications
  resources :community_messages
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/community_message.rb
class CommunityMessage < ActiveRecord::Base
end

app/models/kpi_notification.rb
class KpiNotification < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/community_messages_controller.rb
class CommunityMessagesController < ApplicationController
  before_action :set_community_message, only: [:show, :edit, :update, :destroy]

  # GET /community_messages
  # GET /community_messages.json
  def index
    @community_messages = CommunityMessage.all
  end

  # GET /community_messages/1
  # GET /community_messages/1.json
  def show
  end

  # GET /community_messages/new
  def new
    @community_message = CommunityMessage.new
  end

  # GET /community_messages/1/edit
  def edit
  end

  # POST /community_messages
  # POST /community_messages.json
  def create
    @community_message = CommunityMessage.new(community_message_params)

    respond_to do |format|
      if @community_message.save
        format.html { redirect_to @community_message, notice: 'Community message was successfully created.' }
        format.json { render :show, status: :created, location: @community_message }
      else
        format.html { render :new }
        format.json { render json: @community_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_messages/1
  # PATCH/PUT /community_messages/1.json
  def update
    respond_to do |format|
      if @community_message.update(community_message_params)
        format.html { redirect_to @community_message, notice: 'Community message was successfully updated.' }
        format.json { render :show, status: :ok, location: @community_message }
      else
        format.html { render :edit }
        format.json { render json: @community_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_messages/1
  # DELETE /community_messages/1.json
  def destroy
    @community_message.destroy
    respond_to do |format|
      format.html { redirect_to community_messages_url, notice: 'Community message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_message
      @community_message = CommunityMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_message_params
      params.require(:community_message).permit(:subject, :body, :start_date, :end_date)
    end
end

app/controllers/kpi_notifications_controller.rb
class KpiNotificationsController < ApplicationController
  before_action :set_kpi_notification, only: [:show, :edit, :update, :destroy]

  # GET /kpi_notifications
  # GET /kpi_notifications.json
  def index
    @kpi_notifications = KpiNotification.all
  end

  # GET /kpi_notifications/1
  # GET /kpi_notifications/1.json
  def show
  end

  # GET /kpi_notifications/new
  def new
    @kpi_notification = KpiNotification.new
  end

  # GET /kpi_notifications/1/edit
  def edit
  end

  # POST /kpi_notifications
  # POST /kpi_notifications.json
  def create
    @kpi_notification = KpiNotification.new(kpi_notification_params)

    respond_to do |format|
      if @kpi_notification.save
        format.html { redirect_to @kpi_notification, notice: 'Kpi notification was successfully created.' }
        format.json { render :show, status: :created, location: @kpi_notification }
      else
        format.html { render :new }
        format.json { render json: @kpi_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kpi_notifications/1
  # PATCH/PUT /kpi_notifications/1.json
  def update
    respond_to do |format|
      if @kpi_notification.update(kpi_notification_params)
        format.html { redirect_to @kpi_notification, notice: 'Kpi notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @kpi_notification }
      else
        format.html { render :edit }
        format.json { render json: @kpi_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kpi_notifications/1
  # DELETE /kpi_notifications/1.json
  def destroy
    @kpi_notification.destroy
    respond_to do |format|
      format.html { redirect_to kpi_notifications_url, notice: 'Kpi notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_kpi_notification
      @kpi_notification = KpiNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kpi_notification_params
      params.require(:kpi_notification).permit(:title, :value, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, except: 'show'

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, alert: 'Access denied.'
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: 'User updated.'
    else
      redirect_to users_path, alert: 'Unable to update user.'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, alert: 'Access denied.'
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_messages_helper.rb
module CommunityMessagesHelper
end

app/helpers/kpi_notifications_helper.rb
module KpiNotificationsHelper
end

app/views/community_messages/_form.html.erb
<%= form_for(@community_message) do |f| %>
  <% if @community_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community_message.errors.count, "error") %> prohibited this community_message from being saved:</h2>

      <ul>
      <% @community_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, :style => 'width:100%;' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :style => 'width:100%;' %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.button :submit, :class => 'btn btn-md btn-primary' %>
  </div>
<% end %>

app/views/community_messages/edit.html.erb
<div class="container">
  <h1>Editing Community Message</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @community_message, :class => 'btn btn-sm btn-primary' %> |
  <%= link_to 'Back', community_messages_path, :class => 'btn btn-sm btn-primary' %>
</div>

app/views/community_messages/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Community Messages
                <small>complete list</small>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
          <table class="table">
            <thead>
              <tr>
                <th>Subject</th>
                <th>Body</th>
                <th>Start date</th>
                <th>End date</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @community_messages.each do |community_message| %>
                <tr>
                  <td><%= community_message.subject %></td>
                  <td><%= community_message.body %></td>
                  <td><%= community_message.start_date %></td>
                  <td><%= community_message.end_date %></td>
                  <td><%= link_to 'Show', community_message, :class => 'btn btn-sm btn-primary' %></td>
                  <td><%= link_to 'Edit', edit_community_message_path(community_message), :class => 'btn btn-sm btn-success' %></td>
                  <td><%= link_to 'Destroy', community_message, :class => 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

<br>

<%= link_to 'New Community message', new_community_message_path, :class => 'btn btn-sm btn-primary' %>

app/views/community_messages/new.html.erb
<div class="container">
  <h1>New Community Message</h1>

  <%= render 'form' %>

  <%= link_to 'Back', community_messages_path, :class => 'btn btn-sm btn-primary' %>
</div>

app/views/community_messages/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Subject:</strong>
    <%= @community_message.subject %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @community_message.body %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @community_message.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @community_message.end_date %>
  </p>

  <%= link_to 'Edit', edit_community_message_path(@community_message), :class => 'btn btn-sm btn-primary' %> |
  <%= link_to 'Back', community_messages_path, :class => 'btn btn-sm btn-primary' %>
</div>

app/views/kpi_notifications/_form.html.erb
<%= form_for(@kpi_notification) do |f| %>
  <% if @kpi_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kpi_notification.errors.count, "error") %> prohibited this kpi_notification from being saved:</h2>

      <ul>
      <% @kpi_notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :style => 'width:100%;' %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value, :style => 'width:100%;' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :style => 'width:100%;' %>
  </div>
  <div class="actions">
    <%= f.button :submit, :class => 'btn btn-md btn-primary' %>
  </div>
<% end %>

app/views/kpi_notifications/edit.html.erb
<div class="container">
  <h1>Editing Kpi Notification</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @kpi_notification, :class => 'btn btn-sm btn-primary' %> |
  <%= link_to 'Back', kpi_notifications_path, :class => 'btn btn-sm btn-primary' %>
</div>

app/views/kpi_notifications/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Kpi Notifications
                <small>complete list</small>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Value</th>
                <th>Description</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @kpi_notifications.each do |kpi_notification| %>
                <tr>
                  <td><%= kpi_notification.title %></td>
                  <td><%= kpi_notification.value %></td>
                  <td><%= kpi_notification.description %></td>
                  <td><%= link_to 'Show', kpi_notification, :class => 'btn btn-sm btn-primary' %></td>
                  <td><%= link_to 'Edit', edit_kpi_notification_path(kpi_notification), :class => 'btn btn-sm btn-success' %></td>
                  <td><%= link_to 'Destroy', kpi_notification, :class => 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
<br>

<%= link_to 'New Kpi notification', new_kpi_notification_path, :class => 'btn btn-sm btn-primary' %>

app/views/kpi_notifications/new.html.erb
<div class="container">
  <h1>New Kpi Notification</h1>

  <%= render 'form' %>

  <%= link_to 'Back', kpi_notifications_path, :class => 'btn btn-md btn-primary' %>
</div>

app/views/kpi_notifications/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @kpi_notification.title %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= @kpi_notification.value %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @kpi_notification.description %>
  </p>

  <%= link_to 'Edit', edit_kpi_notification_path(@kpi_notification), :class => 'btn btn-sm btn-primary' %> |
  <%= link_to 'Back', kpi_notifications_path, :class => 'btn btn-sm btn-primary' %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Community Messages', community_messages_path %></li>
<li><%= link_to 'KPI Notifications', kpi_notifications_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rescueme" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rescueme" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
          <% content_for :title do %>About<% end %>
            <h3>About the Website</h3>
            <p>
            Lorem ipsum dolor sit amet, ne laudem lobortis perpetua vis, ex usu vide ponderum, vel partem mollis atomorum ne. Vis viris eligendi cu, nam no option salutatus similique, labore expetendis mei an. An harum populo sensibus per. In mea dictas vocent necessitatibus. An sed invidunt nominati concludaturque, qui unum disputationi no.
            </p>
        </div>
    </div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to('Delete user', user_path(user), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Welcome
                <small>Teddy Bear Heros</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Project One -->
    <div class="row">
        <div class="col-md-7">
          <a href="#" class="portfolio-box">
            <%= image_tag("home-page.png", class: "img-responsive")%>
          </a>
        </div>
        <div class="col-md-5">
            <h3>Teddy Bear Heros</h3>
            <h4>Doing Good While Having Fun</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
            <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
    <!-- /.row -->

    <!-- <hr> -->

    <!-- Project Two -->
    <!-- <div class="row">
        <div class="col-md-7">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/700x300" alt="">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Two</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
            <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div> -->
    <!-- /.row -->

    <!-- <hr> -->

    <!-- Project Three -->
    <!-- <div class="row">
        <div class="col-md-7">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/700x300" alt="">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Three</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
            <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
    <!-- /.row -->

    <!-- <hr> -->

    <!-- Project Four -->
    <!-- <div class="row">

        <div class="col-md-7">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/700x300" alt="">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Four</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, quidem, consectetur, officia rem officiis illum aliquam perspiciatis aspernatur quod modi hic nemo qui soluta aut eius fugit quam in suscipit?</p>
            <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div> -->
    <!-- /.row -->

    <!-- <hr> -->

    <!-- Project Five -->
    <!-- <div class="row">
        <div class="col-md-7">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/700x300" alt="">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Five</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, quo, minima, inventore voluptatum saepe quos nostrum provident ex quisquam hic odio repellendus atque porro distinctio quae id laboriosam facilis dolorum.</p>
            <a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div> -->
    <!-- /.row -->

    <!-- <hr> -->

    <!-- Pagination -->
    <!-- <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">&laquo;</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">&raquo;</a>
                </li>
            </ul>
        </div>
    </div> -->
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; React Games 2016</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>